language: c

#branches:
#  only:
#    - master  # Need to build the nk branch for current pymbar.

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.4    

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "lu3EsyPF+woAABbZyctdFUPfTkAUOyC7k7LsDmWBMrV6ctpvYkomDFS65NAElXDOnmPzxMpn4+f0V2+tNqD4sM/9erDfM2MkJH+tRznNkAAZFoxbxeZCmzV4zSzNvAKlopasHSXt2mbhzbDnhrIToAssQZMHp13pNlBMEq86hKc="

after_success:
  - source devtools/ci/after_sucess.sh
